/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package Cit260.Snake.Frames;

/**
 *
 * @author Kevin
 */
public class HelpMenuFrame extends javax.swing.JFrame {
    MainFrame menu;
    /**
     * Creates new form HelpMenuFrame
     */
    public HelpMenuFrame(MainFrame menu) {
        initComponents();
        this.menu = menu;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        helpMenuPanel = new javax.swing.JPanel();
        helpMenuTitle = new javax.swing.JLabel();
        buttonHelpHowTo = new javax.swing.JLabel();
        buttonHelpBoard = new javax.swing.JLabel();
        buttonHelpScoreing = new javax.swing.JLabel();
        buttonHelpFruit = new javax.swing.JLabel();
        buttonHelpAbout = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        textAreaHelpResults = new javax.swing.JTextArea();
        buttonCloseHelp = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Snake Help Menu");
        setResizable(false);

        helpMenuPanel.setBackground(new java.awt.Color(0, 0, 0));
        helpMenuPanel.setPreferredSize(new java.awt.Dimension(800, 500));
        helpMenuPanel.setSize(new java.awt.Dimension(800, 500));

        helpMenuTitle.setFont(new java.awt.Font("SnakeStitch", 0, 36)); // NOI18N
        helpMenuTitle.setForeground(new java.awt.Color(255, 255, 255));
        helpMenuTitle.setText("Snake  Help  Menu");

        buttonHelpHowTo.setFont(new java.awt.Font("SnakeStitch", 0, 18)); // NOI18N
        buttonHelpHowTo.setForeground(new java.awt.Color(255, 255, 255));
        buttonHelpHowTo.setText("How To Play");
        buttonHelpHowTo.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        buttonHelpHowTo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                buttonHelpHowToMouseClicked(evt);
            }
        });

        buttonHelpBoard.setFont(new java.awt.Font("SnakeStitch", 0, 18)); // NOI18N
        buttonHelpBoard.setForeground(new java.awt.Color(255, 255, 255));
        buttonHelpBoard.setText("TheBoard");
        buttonHelpBoard.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        buttonHelpBoard.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                buttonHelpBoardMouseClicked(evt);
            }
        });

        buttonHelpScoreing.setFont(new java.awt.Font("SnakeStitch", 0, 18)); // NOI18N
        buttonHelpScoreing.setForeground(new java.awt.Color(255, 255, 255));
        buttonHelpScoreing.setText("Scoring");
        buttonHelpScoreing.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        buttonHelpScoreing.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                buttonHelpScoreingMouseClicked(evt);
            }
        });

        buttonHelpFruit.setFont(new java.awt.Font("SnakeStitch", 0, 18)); // NOI18N
        buttonHelpFruit.setForeground(new java.awt.Color(255, 255, 255));
        buttonHelpFruit.setText("Fruit");
        buttonHelpFruit.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        buttonHelpFruit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                buttonHelpFruitMouseClicked(evt);
            }
        });

        buttonHelpAbout.setFont(new java.awt.Font("SnakeStitch", 0, 18)); // NOI18N
        buttonHelpAbout.setForeground(new java.awt.Color(255, 255, 255));
        buttonHelpAbout.setText("About");
        buttonHelpAbout.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        buttonHelpAbout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                buttonHelpAboutMouseClicked(evt);
            }
        });

        textAreaHelpResults.setEditable(false);
        textAreaHelpResults.setBackground(new java.awt.Color(51, 51, 51));
        textAreaHelpResults.setColumns(20);
        textAreaHelpResults.setForeground(new java.awt.Color(255, 255, 255));
        textAreaHelpResults.setLineWrap(true);
        textAreaHelpResults.setRows(5);
        textAreaHelpResults.setWrapStyleWord(true);
        textAreaHelpResults.setMargin(new java.awt.Insets(5, 5, 5, 5));
        jScrollPane1.setViewportView(textAreaHelpResults);

        buttonCloseHelp.setText("OK, got it!");
        buttonCloseHelp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonCloseHelpActionPerformed(evt);
            }
        });

        org.jdesktop.layout.GroupLayout helpMenuPanelLayout = new org.jdesktop.layout.GroupLayout(helpMenuPanel);
        helpMenuPanel.setLayout(helpMenuPanelLayout);
        helpMenuPanelLayout.setHorizontalGroup(
            helpMenuPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(helpMenuPanelLayout.createSequentialGroup()
                .add(14, 14, 14)
                .add(helpMenuPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(buttonHelpAbout)
                    .add(buttonHelpFruit)
                    .add(buttonHelpScoreing)
                    .add(buttonHelpBoard)
                    .add(buttonHelpHowTo))
                .add(18, 18, 18)
                .add(jScrollPane1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 565, Short.MAX_VALUE)
                .add(16, 16, 16))
            .add(org.jdesktop.layout.GroupLayout.TRAILING, helpMenuPanelLayout.createSequentialGroup()
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .add(helpMenuPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(org.jdesktop.layout.GroupLayout.TRAILING, helpMenuPanelLayout.createSequentialGroup()
                        .add(helpMenuTitle)
                        .add(133, 133, 133))
                    .add(org.jdesktop.layout.GroupLayout.TRAILING, helpMenuPanelLayout.createSequentialGroup()
                        .add(buttonCloseHelp)
                        .add(26, 26, 26))))
        );
        helpMenuPanelLayout.setVerticalGroup(
            helpMenuPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(helpMenuPanelLayout.createSequentialGroup()
                .add(45, 45, 45)
                .add(helpMenuTitle)
                .add(71, 71, 71)
                .add(helpMenuPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING, false)
                    .add(helpMenuPanelLayout.createSequentialGroup()
                        .add(buttonHelpHowTo)
                        .add(18, 18, 18)
                        .add(buttonHelpBoard)
                        .add(18, 18, 18)
                        .add(buttonHelpScoreing)
                        .add(18, 18, 18)
                        .add(buttonHelpFruit)
                        .add(18, 18, 18)
                        .add(buttonHelpAbout))
                    .add(jScrollPane1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 182, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, 109, Short.MAX_VALUE)
                .add(buttonCloseHelp)
                .add(21, 21, 21))
        );

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(helpMenuPanel, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .add(helpMenuPanel, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .add(0, 0, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void buttonHelpHowToMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonHelpHowToMouseClicked
        this.textAreaHelpResults.setText("YOU are the snake. You control him. Move him around the board"
                + " and obtain points. Each time you eat fruit the snake grows"
                + " in length. If you control the snake into either the walls"
                + " or yourself, GAME OVER.");
    }//GEN-LAST:event_buttonHelpHowToMouseClicked

    private void buttonHelpBoardMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonHelpBoardMouseClicked
        this.textAreaHelpResults.setText("The board is the area in which the snake moves."
                + " The boards dimensions are 20 rows by 30 columns.");
    }//GEN-LAST:event_buttonHelpBoardMouseClicked

    private void buttonHelpScoreingMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonHelpScoreingMouseClicked
        this.textAreaHelpResults.setText("As you go about the board, your score is increased"
                + " or decreased as you obtain fruit. If you obtain a high score"
                + " in the top 10,your score will be recorded.");
    }//GEN-LAST:event_buttonHelpScoreingMouseClicked

    private void buttonHelpFruitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonHelpFruitMouseClicked
        this.textAreaHelpResults.setText("Fruit is worth 10 points."
                + " Fruit is placed on the board in random locations."
                + " There will only be one fruit on the board"
                + " at a time.");
    }//GEN-LAST:event_buttonHelpFruitMouseClicked

    private void buttonHelpAboutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonHelpAboutMouseClicked
        this.textAreaHelpResults.setText("Snake is a video game which originated during the late 1970s in"
                + " arcades and has maintained popularity since then, becoming a classic."
                + "The Game was invented by Scott McCarthy.");
    }//GEN-LAST:event_buttonHelpAboutMouseClicked

    private void buttonCloseHelpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonCloseHelpActionPerformed
        menu.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_buttonCloseHelpActionPerformed

    /**
     * @param args the command line arguments
     */
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonCloseHelp;
    private javax.swing.JLabel buttonHelpAbout;
    private javax.swing.JLabel buttonHelpBoard;
    private javax.swing.JLabel buttonHelpFruit;
    private javax.swing.JLabel buttonHelpHowTo;
    private javax.swing.JLabel buttonHelpScoreing;
    private javax.swing.JPanel helpMenuPanel;
    private javax.swing.JLabel helpMenuTitle;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea textAreaHelpResults;
    // End of variables declaration//GEN-END:variables
}
