/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package Cit260.Snake.Frames;

import javax.swing.JTextArea;


/**
 *
 * @author Kevin
 */
public class HighScoresFrame extends javax.swing.JFrame {
    MainFrame menu;

    public HighScoresFrame(MainFrame menu) {
        initComponents();
        this.menu = menu;    
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jbody = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        backButton = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        highScoresTextArea = new javax.swing.JTextArea();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jbody.setBackground(new java.awt.Color(0, 0, 0));
        jbody.setMaximumSize(new java.awt.Dimension(800, 500));
        jbody.setMinimumSize(new java.awt.Dimension(800, 500));
        jbody.setPreferredSize(new java.awt.Dimension(800, 500));
        jbody.setSize(new java.awt.Dimension(800, 500));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Cit260/Snake/Images/high-scores-banner.jpg"))); // NOI18N

        backButton.setFont(new java.awt.Font("SnakeStitch", 0, 14)); // NOI18N
        backButton.setForeground(new java.awt.Color(255, 255, 255));
        backButton.setText("Back");
        backButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                backButtonClicked(evt);
            }
        });

        highScoresTextArea.setEditable(false);
        highScoresTextArea.setBackground(new java.awt.Color(51, 51, 51));
        highScoresTextArea.setColumns(20);
        highScoresTextArea.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        highScoresTextArea.setForeground(new java.awt.Color(255, 255, 255));
        highScoresTextArea.setRows(5);
        jScrollPane1.setViewportView(highScoresTextArea);

        jLabel2.setFont(new java.awt.Font("SnakeStitch", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Snake Champions");

        org.jdesktop.layout.GroupLayout jbodyLayout = new org.jdesktop.layout.GroupLayout(jbody);
        jbody.setLayout(jbodyLayout);
        jbodyLayout.setHorizontalGroup(
            jbodyLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jbodyLayout.createSequentialGroup()
                .add(jLabel1)
                .add(0, 0, Short.MAX_VALUE))
            .add(jbodyLayout.createSequentialGroup()
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .add(jLabel2)
                .add(225, 225, 225)
                .add(backButton)
                .add(20, 20, 20))
            .add(jbodyLayout.createSequentialGroup()
                .add(182, 182, 182)
                .add(jScrollPane1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 404, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jbodyLayout.setVerticalGroup(
            jbodyLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jbodyLayout.createSequentialGroup()
                .add(jLabel1)
                .add(jbodyLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jbodyLayout.createSequentialGroup()
                        .add(12, 12, 12)
                        .add(backButton)
                        .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .add(org.jdesktop.layout.GroupLayout.TRAILING, jbodyLayout.createSequentialGroup()
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, 17, Short.MAX_VALUE)
                        .add(jLabel2)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(jScrollPane1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 195, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .add(15, 15, 15))))
        );

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jbody, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jbody, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void backButtonClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_backButtonClicked
        menu.setVisible(true);
        this.setVisible(false);
        this.dispose();
    }//GEN-LAST:event_backButtonClicked

    public JTextArea getHighScoresTextArea() {
        return highScoresTextArea;
    }

    
    
    /**
     * @param args the command line arguments
     */
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel backButton;
    private javax.swing.JTextArea highScoresTextArea;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel jbody;
    // End of variables declaration//GEN-END:variables
}
