/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package Cit260.Snake.Frames;

import Cit260.Snake.Controls.highscore.HighScoreManager;

/**
 *
 * @author Kevin
 */
public class MainFrame extends javax.swing.JFrame {

    /**
     * Creates new form MainMenuFrame
     */
    HelpMenuFrame help = new HelpMenuFrame(this);
    BoardFrame boardFrame = new BoardFrame(this);
    HighScoresFrame highScoresFrame = new HighScoresFrame(this);
    HighScoreManager hm = new HighScoreManager();

    public MainFrame() {
        initComponents();
    }

    public HighScoreManager getHm() {
        return hm;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jpMenuItems = new javax.swing.JPanel();
        buttonHighScores = new javax.swing.JLabel();
        buttonPlay = new javax.swing.JLabel();
        buttonHelpMenu = new javax.swing.JLabel();
        buttonExitProgram = new javax.swing.JLabel();
        jlbackgroundimage = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Snake Main Menu");
        setBackground(new java.awt.Color(0, 0, 0));
        setForeground(new java.awt.Color(0, 0, 0));
        setResizable(false);
        getContentPane().setLayout(new java.awt.GridBagLayout());

        jpMenuItems.setBackground(new java.awt.Color(0, 0, 0));
        jpMenuItems.setOpaque(false);

        buttonHighScores.setFont(new java.awt.Font("SnakeStitch", 0, 24)); // NOI18N
        buttonHighScores.setForeground(new java.awt.Color(255, 255, 255));
        buttonHighScores.setText("High Scores");
        buttonHighScores.setToolTipText("");
        buttonHighScores.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        buttonHighScores.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                buttonHighScoresMouseClicked(evt);
            }
        });

        buttonPlay.setFont(new java.awt.Font("SnakeStitch", 0, 24)); // NOI18N
        buttonPlay.setForeground(new java.awt.Color(255, 255, 255));
        buttonPlay.setText("Play");
        buttonPlay.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        buttonPlay.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                buttonPlayMouseClicked(evt);
            }
        });

        buttonHelpMenu.setFont(new java.awt.Font("SnakeStitch", 0, 24)); // NOI18N
        buttonHelpMenu.setForeground(new java.awt.Color(255, 255, 255));
        buttonHelpMenu.setText("Help Menu");
        buttonHelpMenu.setToolTipText("");
        buttonHelpMenu.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        buttonHelpMenu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                buttonHelpMenuMouseClicked(evt);
            }
        });

        buttonExitProgram.setFont(new java.awt.Font("SnakeStitch", 0, 24)); // NOI18N
        buttonExitProgram.setForeground(new java.awt.Color(255, 255, 255));
        buttonExitProgram.setText("Exit");
        buttonExitProgram.setToolTipText("");
        buttonExitProgram.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        buttonExitProgram.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                buttonExitProgramMouseClicked(evt);
            }
        });

        org.jdesktop.layout.GroupLayout jpMenuItemsLayout = new org.jdesktop.layout.GroupLayout(jpMenuItems);
        jpMenuItems.setLayout(jpMenuItemsLayout);
        jpMenuItemsLayout.setHorizontalGroup(
            jpMenuItemsLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jpMenuItemsLayout.createSequentialGroup()
                .add(209, 209, 209)
                .add(jpMenuItemsLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(buttonHighScores)
                    .add(buttonPlay)
                    .add(buttonHelpMenu)
                    .add(buttonExitProgram))
                .addContainerGap(343, Short.MAX_VALUE))
        );
        jpMenuItemsLayout.setVerticalGroup(
            jpMenuItemsLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(org.jdesktop.layout.GroupLayout.TRAILING, jpMenuItemsLayout.createSequentialGroup()
                .addContainerGap(281, Short.MAX_VALUE)
                .add(buttonPlay)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                .add(buttonHighScores)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                .add(buttonHelpMenu)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                .add(buttonExitProgram)
                .add(67, 67, 67))
        );

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        getContentPane().add(jpMenuItems, gridBagConstraints);

        jlbackgroundimage.setBackground(new java.awt.Color(0, 0, 0));
        jlbackgroundimage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Cit260/Snake/Images/main_background.jpg"))); // NOI18N
        jlbackgroundimage.setToolTipText("");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        getContentPane().add(jlbackgroundimage, gridBagConstraints);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void buttonPlayMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonPlayMouseClicked
        boardFrame.setBoardFrame(boardFrame);
        boardFrame.setHm(hm);
        boardFrame.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_buttonPlayMouseClicked

    private void buttonHighScoresMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonHighScoresMouseClicked
        highScoresFrame.setVisible(true);
        if (hm.startingScores()) {
            hm.addScore("Greg", 0);
        }
        highScoresFrame.getHighScoresTextArea().setText(hm.getHighscoreString());

        this.setVisible(false);
    }//GEN-LAST:event_buttonHighScoresMouseClicked

    private void buttonHelpMenuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonHelpMenuMouseClicked
        help.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_buttonHelpMenuMouseClicked

    private void buttonExitProgramMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonExitProgramMouseClicked
        System.exit(0);
    }//GEN-LAST:event_buttonExitProgramMouseClicked
    /**
     * @param args the command line arguments
     */
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel buttonExitProgram;
    private javax.swing.JLabel buttonHelpMenu;
    private javax.swing.JLabel buttonHighScores;
    private javax.swing.JLabel buttonPlay;
    private javax.swing.JLabel jlbackgroundimage;
    private javax.swing.JPanel jpMenuItems;
    // End of variables declaration//GEN-END:variables
}
